version: "3.9"

services:
  # web:
  #   build: ./app
  #   volumes: 
  #     - './app/:/app'
  #   depends_on:
  #     - postgres
  #   # ports:
  #   #   - 8080:8080
  #   expose:
  #     - 8080
  #   env_file:
  #     - .env
  #   network_mode: "host"

  postgres:
    image: postgres:12.9
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}
      - PGDATA=${PGDATA}
    env_file:
      - .env
    ports:
      - 5433:5432

volumes:
  postgres:
