version: "3.9"

services:
  web:
    build: ./app
    volumes: 
      - './app/:/app'
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - .env

  postgres:
    image: postgres:12.9
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}
      - PGDATA=${PGDATA}
    env_file:
      - .env
    ports:
      - 5433:5432

volumes:
  postgres:
