"""Initialize database

Revision ID: 32f9b5fd1274
Revises: 
Create Date: 2022-03-04 20:33:26.046381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f9b5fd1274'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_country'))
    )
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_name'], ['country.name'], name=op.f('fk_city_country_name_country')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###