"""Change field name

Revision ID: 51e509dbe7c9
Revises: b8c00a9fe0ef
Create Date: 2022-03-04 20:41:35.234375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e509dbe7c9'
down_revision = 'b8c00a9fe0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country', sa.String(), nullable=True))
    op.drop_constraint('fk_city_country_name_country', 'city', type_='foreignkey')
    op.create_foreign_key(op.f('fk_city_country_country'), 'city', 'country', ['country'], ['name'])
    op.drop_column('city', 'country_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_city_country_country'), 'city', type_='foreignkey')
    op.create_foreign_key('fk_city_country_name_country', 'city', 'country', ['country_name'], ['name'])
    op.drop_column('city', 'country')
    # ### end Alembic commands ###