"""Change relationship parameter

Revision ID: b8c00a9fe0ef
Revises: 32f9b5fd1274
Create Date: 2022-03-04 20:37:21.772567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c00a9fe0ef'
down_revision = '32f9b5fd1274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###